### ISSUE TITLE
Proposal: Add a script for auto-TOC generation of README

### ISSUE THREAD

**Issue by tajmone** [yakiradixon/awesome-interactive-fiction#3]
Hi Yakira.

I wanted to call your attention to a couple of scripts I've created for automating TOC generation and source cleanup in markdown documents inside my repos:

https://github.com/tajmone/purebasic-archives/tree/master/repo-maintainance-tools

Since the TOC of **awesome-interactive-fiction** is heading to grow longer and longer in time, I could create a simplified variant of these scripts, to handle the single README of this repo with just a click. The presence of a batch script shouldn't interfere with the overall repo.

At the link provided above, you'll find the rationale behind these scripts, and their advantages in cooperative work.

If you give me the OK to go, I'll modify the script and make a PR for it.

Creating a *nix shell variant of the script shouldn't be a problem either, and the tools invoked by it are cross-platform.

Best regards,

Tristano

**Comment by yakiradixon** [comment]
Hey Tristano,

I'm totally fine with having some small, simple tools for repo maintenance.

**Comment by tajmone** [comment]
Thanks a lot for adding me to the repo participants!

I'll prepare the script, license it public domain and publish it!

PS: I was a bit caught up in these days with some publishing work, and didn't find much time to add more resource.

**Comment by tajmone** [comment]
Added! (and tested)

**Comment by yakiradixon** [comment]
Done in commit 02a3bd0
